version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.18.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:4.18.1
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
    shm_size: 2gb
    networks:
      - grid
  chrome-video:
      image: selenium/video:latest
      container_name: chrome-video
      depends_on:
        - chrome
      environment:
        - DISPLAY_CONTAINER_NAME=chrome-node
        - FILE_NAME=chrome_session.mp4
      volumes:
        - ./videos:/videos
      networks:
        - grid

  firefox:
    image: selenium/node-firefox:4.18.1
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
    shm_size: 2gb
    networks:
      - grid

networks:
  grid:
    driver: bridge